version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: quipuq
      POSTGRES_PASSWORD: quipuq
      POSTGRES_DB: quipuq
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
  api:
    build: ../../services/api
    depends_on: [postgres, redis]
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
  notification:
    build: ../../services/notification
    environment:
      - PORT=4000
    ports:
      - '4000:4000'
  reniec:
    build: ../../services/reniec-adapter
    environment:
      - PORT=4100
    ports:
      - '4100:4100'
  admin:
    build: ../../apps/admin
    ports:
      - '5173:5173'
  operator:
    build: ../../apps/operator
    ports:
      - '5174:5173'
  kiosk:
    build: ../../apps/kiosk-touch
    ports:
      - '5175:5173'
  monitor:
    build: ../../apps/monitor
    ports:
      - '5176:5173'
  nginx:
    image: nginx:1.25
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on: [api, notification, reniec]
