version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quipuq
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      retries: 5
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 5
    ports:
      - '6379:6379'

  api:
    build: ../../services/api
    env_file: .env
    environment:
      - PORT=${API_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000']
      interval: 10s
      retries: 5
    ports:
      - '${API_PORT:-3000}:3000'

  notification:
    build: ../../services/notification
    env_file: .env
    environment:
      - PORT=${NOTIFICATION_PORT}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3001']
      interval: 10s
      retries: 5
    ports:
      - '${NOTIFICATION_PORT:-3001}:3001'

  reniec-adapter:
    build: ../../services/reniec-adapter
    env_file: .env
    environment:
      - PORT=${RENIEC_ADAPTER_PORT}
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3002']
      interval: 10s
      retries: 5
    ports:
      - '${RENIEC_ADAPTER_PORT:-3002}:3002'

  admin:
    build: ../../apps/admin
    ports:
      - '5173:80'

  operator:
    build: ../../apps/operator
    ports:
      - '5174:80'

  kiosk:
    build: ../../apps/kiosk-touch
    ports:
      - '5175:80'

  monitor:
    build: ../../apps/monitor
    ports:
      - '5176:80'

  nginx:
    image: nginx:1.25
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      api:
        condition: service_healthy
      notification:
        condition: service_healthy
      reniec-adapter:
        condition: service_healthy
      admin:
        condition: service_started
      operator:
        condition: service_started
      kiosk:
        condition: service_started
      monitor:
        condition: service_started
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost']
      interval: 10s
      retries: 5
    ports:
      - '8080:80'
